export const PLUGIN_NAME = "homebridge-frisquet-connect";
export const PLATFORM_NAME = "FrisquetConnect";
export const DEFAULT_HOSTNAME = "https://fcutappli.frisquet.com/api/v1";
export const DEFAULT_APP_ID = "f1VQtboNAac";
export const DEFAULT_USER_AGENT = "Frisquet%20Connect/16 CFNetwork/974.2.1 Darwin/18.0.0";
export const DEFAULT_HISTORY_DISABLED = false;
export const DEFAULT_HISTORY_INTERVAL = 15 * 60; // 15min
export const DEFAULT_HEATING_DELTA = 10; // 1°C
export const { HOMEBRIDGE_FRISQUET_CONNECT_PASSWORD } = process.env;
